# Generated by Django 5.1.2 on 2024-11-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subscriptionplan_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the plan in days', null=True),
        ),
    ]
