# Generated by Django 5.1.2 on 2024-11-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subscriptionplan_duration_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order_priority']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order_priority',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
