# Generated by Django 5.1.2 on 2024-11-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_premium',
        ),
    ]
